### PR TITLE
Adding lodash variable if available

### PR DESCRIPTION
**Pull request by kamlekar**
The previous code was overriding the `_` variable of lodash.

### CODE REVIEW

**Comment by kamlekar** [comment]
@JiangJie please review this pull request.

**Comment by JiangJie** [comment]
Thanks for your PR. Actually, it would be better judging whether `_.escape` is a effective function.

**Comment by kamlekar** [comment]
@JiangJie thanks for merging. I don't know much about what exactly you are doing with `_.escape`. It will be better if you do those changes and bump the version. So that I can use it with lodash/underscore plugins. Thanks.

**Comment by kamlekar** [comment]
Hi @JiangJie any update on this?

>  It will be better if you do those changes and bump the version. So that I can use it with lodash/underscore plugins. Thanks.

**Comment by kamlekar** [comment]
Hi @JiangJie Unfortunately :), I still want this to be released. Please do this.

**Pull request merged**
